# Generated by Django 5.1.3 on 2024-11-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('file_type', models.CharField(max_length=10)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('file', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
