# Generated by Django 5.1.3 on 2025-04-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
    ]
